# Generated by Django 2.2.2 on 2019-06-26 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_author', models.CharField(help_text='Enter the name of the author', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category', models.CharField(help_text='Enter a book category (e.g. CSS, HTML, Javascript, Python, R)', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_url', models.URLField(help_text='Enter the unique URL of the book.', unique=True)),
                ('book_description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('db_date_added', models.DateTimeField(auto_now_add=True)),
                ('book_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BookAuthor')),
                ('book_category', models.ManyToManyField(help_text='Select categories for this book', to='core.Category')),
            ],
            options={
                'ordering': ['-db_date_added'],
            },
        ),
    ]
